groups:
- name: nexon-alerts
  rules:
  - alert: HighErrorRate
    expr: |
      (sum(rate(nexon_http_requests_total{status_code=~"5.."}[5m]))
       / sum(rate(nexon_http_requests_total[5m])))
      > 0.01
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High API error rate (>1%)"
  - alert: HighLatency99
    expr: |
      histogram_quantile(0.99,
        sum(rate(nexon_http_request_duration_seconds_bucket[5m])) by (le))
      > 1
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "API p99 latency > 1s"
