name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install build tools
        run: |
          pip install build twine

      - name: Build & Publish PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m build
          twine upload dist/*

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        env:
          IMAGE_NAME: nexon/cli
          VERSION: ${{ github.ref_name }}
        run: |
          docker build -t $IMAGE_NAME:${VERSION#v} .
          docker push $IMAGE_NAME:${VERSION#v}
          docker tag $IMAGE_NAME:${VERSION#v} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
